# Generated by Django 5.1.5 on 2025-06-11 12:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flag_image/')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('employees', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('all_disclosures', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('completed_disclosures', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('view_number', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disclosures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('filesCount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('filesSizes', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=40, null=True)),
                ('view_number', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('zip_link', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 6, 11, 12, 4, 54, 99477, tzinfo=datetime.timezone.utc))),
                ('status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='main.company')),
                ('tags', models.ManyToManyField(blank=True, to='main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='DisclosuresPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshots', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('disclosures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.disclosures')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filter')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='filters',
            field=models.ManyToManyField(blank=True, through='main.CompanyFilter', to='main.filter'),
        ),
        migrations.CreateModel(
            name='DisclosuresTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disclosures')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, through='main.CompanyTag', to='main.tag'),
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('isLeaf', models.BooleanField(default=False)),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.disclosures')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.treenode')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.treenode')),
            ],
        ),
    ]
