# Generated by Django 5.1.5 on 2025-06-11 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 12, 18, 27, 333451, tzinfo=datetime.timezone.utc)),
        ),
    ]
