# Generated by Django 5.1.5 on 2025-06-12 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_disclosures_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_image/'),
        ),
        migrations.AlterField(
            model_name='disclosures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 12, 49, 8, 844602, tzinfo=datetime.timezone.utc)),
        ),
    ]
