# Generated by Django 5.1.5 on 2025-06-13 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_logo_alter_disclosures_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disclosures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 11, 34, 29, 586582, tzinfo=datetime.timezone.utc)),
        ),
    ]
